#!/usr/bin/env dash

"/home/main/dot/dot/d_mail/src/notmuch.sh" tag

notmuch tag --batch <"/home/main/.config/notmuch/default/hooks/post_new/archive.rule"
notmuch tag --batch <"/home/main/.config/notmuch/default/hooks/post_new/sent.rule"
