#!/usr/bin/env dash

tag() {
    local script_path
    script_path="$HOME/.config/notmuch/default/hooks/tag/"

    notmuch tag --batch <"${script_path}/builtin.rule"
    notmuch tag --batch <"${script_path}/archive.rule"
    notmuch tag --batch <"${script_path}/sent.rule"
}

main() {
    tag

    unset -f tag
}
main
unset -f main
